### ISSUE TITLE
Umbrella header warning when use_modular_headers! is used

### ISSUE THREAD

**Issue by krze** [SDWebImage/SDWebImage#2747]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 12.2
 SDWebImage Version      | 5.0.6
 Integration Method      | cocoapods
 Xcode Version           | Xcode 10.2.1
 Repro rate              | all the time (100%)
 Repro with our demo prj | n/a
 Demo project link       | n/a

### Issue Description and Steps
When SDWebImage is installed via Cocoapods with `use_modular_headers!` set in the podfile, a warning is thrown about missing header files. Our project treats warnings as errors, so in our case this stops us from compiling. Trying to silence the error via `-Wno-incomplete-umbrella` flags in the `OTHER_SWIFT_FLAGS` setting doesn't seem to silence it either.

<img width="361" alt="Screen Shot 2019-06-05 at 6 37 23 PM" src="https://user-images.githubusercontent.com/10662717/58995310-b664ad80-87c1-11e9-8a36-f45256ddb70b.png">

These all seem to be private files, which makes sense that they wouldn't be imported. However this wasn't a problem with 4.x.x with `use_modular_headers!`. This problem does not occur if you set `use_frameworks!`

I had to silence the warning by adding those headers to the umbrella file.

**Comment by dreampiggy** [comment]
All of your listed headers, are private headers. They are not public. So they should not be listed in umbrella headers.

And this is CocoaPods's bug, it does not recognize the `private_header_files` as Private. Instead, they treat these as `Projust` Headers.

See: https://github.com/CocoaPods/CocoaPods/issues/7598#issuecomment-496849032

Wait for CocoaPods for fixiing this. For us, we can not do anything. You can disable the `-Werror=-incomplete-umbrella` if you treat all warnings as error.

**Comment by dreampiggy** [comment]
> However this wasn't a problem with 4.x.x with use_modular_headers!. This problem does not occur if you set use_frameworks!

It's definitely OK. Because 4.x does not have any private headers.

**Comment by dreampiggy** [comment]
Or, if you still really want to use need Static Framework, write a custom script to change the `Mach O Type` when using `use_frameworks!`.

```ruby
post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['MACH_O_TYPE'] = 'staticlib'
		end
	end
end
```

**Comment by dreampiggy** [comment]
> Trying to silence the error via -Wno-incomplete-umbrella flags in the OTHER_SWIFT_FLAGS setting doesn't seem to silence it either.
This should work. Did you use this warning flags on your Application or Test target. It's wrong. For CocoaPods, you should set this warning flags, in the Pods targets. See there are `Pods.xcodeproj` and select `SDWebImage` target, change the build settings there.

**Comment by krze** [comment]
It turns out that the `-Wno-incomplete-umbrella` flag needed to be added to "Other C Flags" not "Other Swift Flags" in order to suppress the warning. This is working now. Thanks for the help
