### ISSUE TITLE
Adhere to Apple's Data Collection / App Privacy details

### ISSUE THREAD

**Issue by bpoplauschi** [SDWebImage/SDWebImage#3126]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/rs/SDWebImage/blob/master/.github/CONTRIBUTING.md)
* [x] I have read the [Documentation](http://cocoadocs.org/docsets/SDWebImage/)
* [x] I have searched for a similar issue in the [project](https://github.com/rs/SDWebImage/issues) and found none

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | all
 Platform Version        | -
 SDWebImage Version      | latest

### Apple's Data Collection / App Privacy details

Apple is changing the submission process by requiring app developers to describe their data collection and privacy practices in App Store Connect.
For this process to run smoothly, they have asked SDK developers to provide the same details so that app developers can compile a list from all their dependencies and their explicit ones.
See details:
- https://developer.apple.com/app-store/app-privacy-details/
- https://developer.apple.com/app-store/user-privacy-and-data-use/
- similar thread on the Firebase SDK GH proj: https://github.com/firebase/firebase-ios-sdk/issues/5928

### Todo

What's required of us at this point is to gather that data and make it available on our documentation (Apple may link to it).
- [x] compile list of SDWebImage's privacy practices
- [x] make it available and explicit within our docs and repo (as links)

### Prototype
I have started working on a prototype which I added as static web pages to our github.io docs:
https://sdwebimage.github.io/DataCollection/index.html (also linked from the [main docs page](https://sdwebimage.github.io)).

At my first review round, I couldn't find any private data we are collecting from the users, but I may have missed something.
@SDWebImage/collaborators please go through this list https://sdwebimage.github.io/DataCollection/index.html and let's discuss if there is any data there that you think we may be collecting in some place of our SDK.

(for example I have considered our `MapKit` subspec might be collecting user location, but as I reviewed that code, we are not gathering the user location or any other data there).

**Comment by dreampiggy** [comment]
SDWebImage latest version(5.9.4) does not collect any of Use Data listed in that page.

The only information we get, it's the CPU Core count, and RAM usage. These is not considered as privacy data.

**Comment by bpoplauschi** [comment]
@dreampiggy great, I think the same, but I thought maybe I'm missing something.
I will create a PR where I add a section to our Readme.md about this Data Collection and link to the same list I linked above.

**Comment by bpoplauschi** [comment]
Added link to our Readme (section https://github.com/SDWebImage/SDWebImage#data-collection-practices)

**Comment by simonmaddox** [comment]
> The only information we get, it's the CPU Core count, and RAM usage. These is not considered as privacy data.

Wouldn’t that come under Diagnostic Data not linked to the user?

**Comment by dreampiggy** [comment]
SDWebImage does not collect data, and does not send to anyone. And you can not link CPU core count to any User.

**Comment by simonmaddox** [comment]
Maybe I’m misunderstanding? You said above “the only information we get”, which suggests this data _is_ sent somewhere. That would require selecting this option in “Other Diagnostic Data”, wouldn’t it?

![Image 27-11-2020 at 11 08](https://user-images.githubusercontent.com/34273/100443119-0663be00-30a1-11eb-80bb-27b0700bc21f.jpeg)

**Comment by dreampiggy** [comment]
Choose "No".

**Comment by bpoplauschi** [comment]
@simonmaddox sorry if the thread above is a bit confusing. SDWebImage does not collect any data from the user, it uses no backend or send data to any service. The library simply handles the downloading caching and rendering of various images types.

@dreampiggy I think you need to explain what you mean with
> The only information we get, it's the CPU Core count, and RAM usage.

I can't recall getting those info in any scenario, but even if we do, I assume we just call some low level API to get those and decide on an appropriate concurrency policy for the image processing.
Can you please explain?

**Comment by dreampiggy** [comment]
I read Apple's explaination again:

> “Collect” refers to transmitting data off the device in a way that allows you and/or your third-party partners to access it for a period longer than what is necessary to service the transmitted request in real time.

SDWebImage does not transmit any data. So all of the answer should be **Does not collect data**.

Not what you think @simonmaddox  `Collect data but not linked to user privacy`

**Comment by bpoplauschi** [comment]
@dreampiggy I have to insist, as you didn't provide the answer I was hoping.
Why did you say "The only information we get, it's the CPU Core count, and RAM usage."?
Are we doing this in the code and if so, where?

**Comment by dreampiggy** [comment]
The calculation of frame cache based on current RAM usage.

https://github.com/SDWebImage/SDWebImage/blob/master/SDWebImage/Core/SDAnimatedImagePlayer.m#L386


My falult. You can forgot all the things I said above. This is not related to Apple's privacy data rule.
